version: '3'

services:
  api:
    container_name: car-api
    build: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/car_api
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=pgsql
      - KEYCLOAK_REAM=car-realm
      - KEYCLOAK_HOST=http://keycloak:8443
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - car-network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=car_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgsql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d car_api -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - car-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8443:8080"
    command:
      - start-dev
    networks:
      - car-network

networks:
  car-network:
    driver: bridge