spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car-api
    username: postgres
    password: pgsql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true