spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}
  clientId: ${KEYCLOAK_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  username: ${KEYCLOAK_USERNAME}
  password: ${KEYCLOAK_PASSWORD}
