spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/car_api}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:pgsql}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST:http://localhost:8443}/realms/${KEYCLOAK_REALM:car-realm}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_HOST:http://localhost:8443}/realms/${KEYCLOAK_REALM:car-realm}

keycloak:
  realm: ${KEYCLOAK_REALM:car-realm}
  host: ${KEYCLOAK_HOST:http://localhost:8443}
  clientId: ${KEYCLOAK_ID:car-api}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:changeme}
  username: ${KEYCLOAK_USERNAME:admin}
  password: ${KEYCLOAK_PASSWORD:car-api}
