version: '3'

services:
  api:
    container_name: car-api
    image: ramoncunha/carapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - car-network

  postgres:
    container_name: postgres
    image: ramoncunha/carapi-postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - car-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8443:8080"
    command:
      - start-dev
    networks:
      - car-network

networks:
  car-network: