version: '3'

services:
  postgres:
    build:
      context: .
    container_name: postgres
    restart: always
#    volumes:
#      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"